
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/banking_app?allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: M@hato123
    driver-class-name: com.mysql.cj.jdbc.Driver
    initialization-mode: always
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL8Dialect

security:
  jwt:
    secret-key: ${JWT_SECRET_KEY:95276ee738ca693ec083224d18ba616c06b3504c23882ae16ebca857b037840e}
    expiration-time: ${JWT_EXPIRATION_TIME:86400000}