# Frontend Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: ermukeshmahato/frontend:latest
          ports:
            - containerPort: 3000  # Expose port 3000 within the container

---
# Frontend Service (with NodePort to expose outside the cluster)
apiVersion: v1
kind: Service
metadata:
  name: frontend
spec:
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 3000  # Expose service on port 3000 inside the cluster
      targetPort: 3000  # Container port (the app is running on port 3000)
      nodePort: 30001  # Expose service on port 30001 outside the cluster
  type: NodePort  # Expose service outside the cluster
