# Frontend Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: 3 # Adjusted replicas to 1 based on your requirement
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: ermukeshmahato/frontend:latest  # Ensure this image is available in the registry
          ports:
            - containerPort: 3000  # Expose the app inside the container on port 3000

---
# Frontend Service (NodePort to expose outside the cluster)
apiVersion: v1
kind: Service
metadata:
  name: frontend
spec:
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 3000  # The port inside the cluster
      targetPort: 3000  # Container port where Vite app is running
      nodePort: 30001    # External port to access from outside the cluster
  type: NodePort 
 
